import type { AlpinePackage } from './types';

export const packages: AlpinePackage[] = [
  {
    name: 'nginx',
    version: '1.20.2-r0',
    description: 'A high performance free open source web server and reverse proxy server',
    dependencies: ['pcre', 'openssl', 'zlib', 'nginx-conf', 'nginx-openrc'],
    repo: 'main',
    arch: 'x86_64',
    url: 'https://nginx.org/',
    license: 'BSD-2-Clause',
    size: '792.00 kB',
    installSize: '2.00 MB',
    origin: 'nginx',
    maintainer: 'Natanael Copa <ncopa@alpinelinux.org>',
    buildTime: '2023-01-15T12:00:00Z',
  },
  {
    name: 'docker',
    version: '20.10.12-r0',
    description: 'The open-source application container engine',
    dependencies: ['containerd', 'runc', 'docker-proxy', 'iptables'],
    repo: 'community',
    arch: 'x86_64',
    url: 'https://www.docker.com/',
    license: 'Apache-2.0',
    size: '35.00 MB',
    installSize: '150.00 MB',
    origin: 'docker',
    maintainer: 'Moby <moby@mobyproject.org>',
    buildTime: '2023-02-01T10:00:00Z',
  },
  {
    name: 'git',
    version: '2.34.1-r0',
    description: 'Distributed version control system',
    dependencies: ['pcre2', 'curl', 'openssl', 'zlib'],
    repo: 'main',
    arch: 'x86_64',
    url: 'https://git-scm.com/',
    license: 'GPL-2.0-only',
    size: '5.50 MB',
    installSize: '27.00 MB',
    origin: 'git',
    maintainer: 'Jakub Jirutka <jakub@jirutka.cz>',
    buildTime: '2023-02-10T18:30:00Z',
  },
  {
    name: 'python3',
    version: '3.9.9-r0',
    description: 'The Python 3 programming language',
    dependencies: ['libffi', 'openssl', 'sqlite-libs', 'zlib'],
    repo: 'main',
    arch: 'x86_64',
    url: 'https://www.python.org/',
    license: 'Python-2.0',
    size: '15.00 MB',
    installSize: '75.00 MB',
    origin: 'python3',
    maintainer: 'Python Upstream <python@python.org>',
    buildTime: '2023-01-20T09:00:00Z',
  },
  {
    name: 'nodejs',
    version: '16.13.2-r0',
    description: 'JavaScript runtime built on V8',
    dependencies: ['c-ares', 'http-parser', 'libuv', 'openssl', 'zlib'],
    repo: 'community',
    arch: 'x86_64',
    url: 'https://nodejs.org/',
    license: 'MIT',
    size: '20.00 MB',
    installSize: '90.00 MB',
    origin: 'nodejs',
    maintainer: 'Node.js <build@nodejs.org>',
    buildTime: '2023-02-05T14:20:00Z',
  },
  {
    name: 'postgresql',
    version: '14.1-r0',
    description: 'A powerful, open source object-relational database system',
    dependencies: ['icu-libs', 'openssl', 'readline', 'zlib'],
    repo: 'main',
    arch: 'x86_64',
    url: 'https://www.postgresql.org/',
    license: 'PostgreSQL',
    size: '18.00 MB',
    installSize: '80.00 MB',
    origin: 'postgresql',
    maintainer: 'PostgreSQL Global Development Group <pgsql-bugs@lists.postgresql.org>',
    buildTime: '2022-12-25T05:00:00Z',
  },
    {
    name: 'redis',
    version: '6.2.6-r0',
    description: 'An in-memory data structure store',
    dependencies: [],
    repo: 'community',
    arch: 'x86_64',
    url: 'https://redis.io/',
    license: 'BSD-3-Clause',
    size: '1.20 MB',
    installSize: '4.50 MB',
    origin: 'redis',
    maintainer: 'Redis Labs <community@redislabs.com>',
    buildTime: '2023-03-12T11:45:00Z',
  },
  {
    name: 'htop',
    version: '3.1.2-r0',
    description: 'An interactive process viewer',
    dependencies: ['ncurses-libs'],
    repo: 'community',
    arch: 'x86_64',
    url: 'https://htop.dev/',
    license: 'GPL-2.0-only',
    size: '150.00 kB',
    installSize: '450.00 kB',
    origin: 'htop',
    maintainer: 'Hisham Muhammad <hisham@hisham.hm>',
    buildTime: '2022-11-30T22:10:00Z',
  },
  {
    name: 'neofetch',
    version: '7.1.0-r0',
    description: 'A fast, highly customizable system information script',
    dependencies: ['bash'],
    repo: 'community',
    arch: 'x86_64',
    url: 'https://github.com/dylanaraps/neofetch',
    license: 'MIT',
    size: '100.00 kB',
    installSize: '400.00 kB',
    origin: 'neofetch',
    maintainer: 'Dylan Araps <dylan.araps@gmail.com>',
    buildTime: '2022-10-10T10:10:10Z',
  },
  {
    name: 'gcc',
    version: '10.3.1_git20211027-r0',
    description: 'The GNU Compiler Collection',
    dependencies: ['binutils', 'gmp', 'isl', 'mpc1', 'mpfr4'],
    repo: 'main',
    arch: 'x86_64',
    url: 'https://gcc.gnu.org/',
    license: 'GPL-3.0-or-later',
    size: '40.00 MB',
    installSize: '200.00 MB',
    origin: 'gcc',
    maintainer: 'GNU GCC <gcc@gcc.gnu.org>',
    buildTime: '2023-03-20T08:00:00Z',
  },
  {
    name: 'make',
    version: '4.3-r0',
    description: 'The GNU Make utility to maintain groups of programs',
    dependencies: [],
    repo: 'main',
    arch: 'x86_64',
    url: 'https://www.gnu.org/software/make/',
    license: 'GPL-3.0-or-later',
    size: '200.00 kB',
    installSize: '600.00 kB',
    origin: 'make',
    maintainer: 'GNU <make-bug@gnu.org>',
    buildTime: '2022-09-01T00:00:00Z',
  },
  {
    name: 'curl',
    version: '7.80.0-r0',
    description: 'A tool to transfer data from or to a server',
    dependencies: ['ca-certificates', 'c-ares', 'libssh2', 'nghttp2-libs', 'openssl', 'zlib'],
    repo: 'main',
    arch: 'x86_64',
    url: 'https://curl.se/',
    license: 'curl',
    size: '250.00 kB',
    installSize: '700.00 kB',
    origin: 'curl',
    maintainer: 'Daniel Stenberg <daniel@haxx.se>',
    buildTime: '2023-03-15T19:50:00Z',
  },
  {
    name: 'vim',
    version: '8.2.3995-r0',
    description: 'Vi IMproved, a programmers text editor',
    dependencies: ['ncurses-libs'],
    repo: 'community',
    arch: 'x86_64',
    url: 'https://www.vim.org/',
    license: 'Vim',
    size: '10.00 MB',
    installSize: '45.00 MB',
    origin: 'vim',
    maintainer: 'Bram Moolenaar <Bram@vim.org>',
    buildTime: '2023-04-01T12:00:00Z',
  }
];
